name: ğŸ“‚ .NET Build & Sync Demo
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: â¬ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: ğŸ“¦ Restore dependencies
      run: dotnet restore VIOVNL.Flowy.Demo/VIOVNL.Flowy.Demo.csproj
    - name: ğŸ—ï¸ Build
      run: dotnet build VIOVNL.Flowy.Demo/VIOVNL.Flowy.Demo.csproj --configuration Release --no-restore
    - name: ğŸ“© Publish to Release folder
      run: dotnet publish VIOVNL.Flowy.Demo/VIOVNL.Flowy.Demo.csproj -c Release --no-build --output ./Release
    - name: ğŸ• Sync files from Release folder to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_IP }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./Release/
        server-dir: ./
    - name: ğŸ›œ Install SSHPass
      run: sudo apt-get install -y sshpass
    - name: ğŸ“¤ SSH into server and restart service
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} "systemctl restart ${{ secrets.SERVICE_NAME}}"
